# roles/base/tasks/admin.yml
#
# Settings regarding the admin user
---
- name: Copy sudoers.d file
  copy:
    src: "{{ base_dotfiles_dest }}/src/sudoers.d/anton"
    dest: "/etc/sudoers.d/"
    owner: root
    group: root
    mode: "0640"
  tags: sudoers
  become: yes
