# roles/base/tasks/bash.yml
---
- name: Bash | Symlinking .bashrc
  file:
    src: "{{ base_dotfiles_dest }}/src/.bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: link
    force: yes

- name: Bash | Symlinking .bash_profile
  file:
    src: "{{ base_dotfiles_dest }}/src/.bash_profile"
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    state: link
    force: yes

- name: Bash | Symlinking .bashrc.d
  file:
    src: "{{ base_dotfiles_dest }}/src/.bashrc.d"
    dest: "{{ ansible_env.HOME }}/.bashrc.d"
    state: link
    force: yes

- name: Bash | Make scripts located ad ".bashrc.d/" executable
  file:
    path: "{{ item }}"
    mode: +x
  with_fileglob:
    - "{{ ansible_env.HOME }}/.bashrc.d/*"
