# roles/base/tasks/bash.yml
---
- name: Neovim | Symlinking .config/nvim/
  file:
    src: "{{ base_dotfiles_dest }}/src/.config/nvim/"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    state: link
    force: yes

- name: Neovim | Installing pynvim
  pip:
    name: pynvim
    executable: pip3

- name: Neovim | Installing neovim npm
  npm:
    name: neovim
    global: yes
  become: yes
