# roles/base/tasks/bash.yml
---
- name: Tmux| Symlinking .tmux.conf
  file:
    src: "{{ base_dotfiles_dest }}/src/.tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link
    force: yes

- name: Tmux | Symlinking .config/tmux/
  file:
    src: "{{ base_dotfiles_dest }}/src/.config/tmux/"
    dest: "{{ ansible_env.HOME }}/.config/tmux"
    state: link
    force: yes

- name: Tmux | Ensure plugin directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/tmux/plugins/"
    state: directory
