[font]
size = 12

[font.bold]
family = "Ubuntu Mono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Ubuntu Mono Nerd Font"

[font.normal]
family = "Ubuntu Mono Nerd Font"

[font.offset]
x = 0
y = 0
