# roles/gnome/tasks/firefox.yml
---
- name: Firefox | Ensure chrome directory exists
  file:
    path: "{{ gnome_firefox_theme_path }}"
    state: directory

- name: Firefox | Apply custom theme
  copy:
    src: "{{ gnome_firefox_theme_src }}"
    dest: "{{ gnome_firefox_theme_file_path }}"
