# roles/gnome/tasks/packages.yml
---
- name: Packages | Ensure all specified packages are installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - "{{ gnome_install_packages }}"
  become: true

- name: Packages | Install role dependencies (pip)
  pip:
    name: "{{ gnome_role_dependencies_pip }}"
    state: latest
