# roles/gnome/tasks/wallpaper.yml
---
- name: Wallpaper | Make sure the wallpaper directory exists ({{ gnome_wallpaper_dir }})
  file:
    path: "{{ gnome_wallpaper_dir }}"
    state: directory
    mode: 0755

- name: Wallpaper | Symlinking wallpaper directory ({{ gnome_wallpaper_dir }})
  file:
    src: "{{ gnome_wallpaper_src }}"
    dest: "{{ gnome_wallpaper_dir }}"
    state: link
    force: yes

- name: Wallpaper | Set the specified wallpaper ({{ gnome_specified_wallpaper }}) (light)
  dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ gnome_specified_wallpaper }}'"

- name: Wallpaper | Set the specified wallpaper ({{ gnome_specified_wallpaper }}) (dark)
  dconf:
    key: /org/gnome/desktop/background/picture-uri-dark
    value: "'file://{{ gnome_specified_wallpaper }}'"
