#!/usr/bin/env bash

# enable color support of ls and grep
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# utils
alias md='mkdir'
alias rd='rm -rfv'
alias cp='cp -r'

# reboot and power off
alias gg='sudo systemctl poweroff'
alias gj='sudo systemctl reboot'

# reload .bashrc
alias reload='source ~/.bashrc'

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias projects='cd $HOME/Projects/'

# shorts
alias c='clear'
alias q='exit'
alias :q='exit'
alias :wq='exit'
alias :x='exit'
alias h='builtin history | less'
alias hg='builtin history | grep'
alias open='xdg-open'

# Cat
alias cat='bat'

# git
alias g='git'

# vim
alias vim=nvim # Use nvim instead of `vim`
               # To use regular `vim` you can type `\vim `
alias vi=vim
alias svi="sudo -E vim"
alias vis='vim "+set si"'

# Python
alias py='python'

# net
alias wget='wget -c'
alias ping='ping -c 5'

# find
alias f='find . -iname'
alias fif='find . -type f -iname'
alias fid='find . -type d -iname'

# Vagrant
alias v='vagrant'
alias vD='vagrant destroy --force'
alias vd='vagrant destroy'
alias vdu='vagrant destroy --force && vagrant up'
alias vh='vagrant halt'
alias vp='vagrant provision'
alias vr='vagrant reload'
alias vS='vagrant ssh'
alias vs='vagrant status'
alias vu='vagrant up'

# DNF
alias i='sudo dnf install'
alias u='sudo dnf upgrade'

# SSH without adding the target host to ~/.ssh/known_hosts
alias sshh='ssh -o UserKnownHostsFile=/dev/null '
