#!/usr/bin/env bash

# enable color support of ls and grep
if [ -x /usr/bin/dircolors ]; then
   test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
   alias ls='ls --color=auto'
   alias grep='grep --color=auto'
   alias fgrep='fgrep --color=auto'
   alias egrep='egrep --color=auto'
fi

# LSDelux
alias ls='lsd'

# ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# utils 
alias md='mkdir'
alias rd='rm -rfv'
alias cp='cp -r'

# reboot and power off
alias gg='doas systemctl poweroff'
alias gj='doas systemctl reboot'

# reload .bashrc
alias reload='source ~/.bashrc'

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias projects='cd $HOME/Projects/'

# shorts
alias c='clear'
alias q='exit'
alias h='builtin history | less'
alias hg='builtin history | grep'
alias open='xdg-open'

# info
alias meminfo='free -mlth'

# git
alias g='git'

# vim
alias vi=vim
alias svi="sudo -E vim"
alias vis='vim "+set si"'
alias edit=vim

# net
alias ports='netstat -tulanp'
alias wget='wget -c'
alias ping='ping -c 5'

# find
alias f='find . -iname'
alias fif='find . -type f -iname'
alias fid='find . -type d -iname'

