#!/bin/bash

history() {
    builtin history | \
        awk '{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}' | \
        grep -v "./" | \
        column -c3 -s " " -t | \
        sort -nr | \
        nl | \
        head -n10
}

cd() {
    [[ -z "${1}" ]] && builtin cd "${HOME}" && ls && return
    [[ "${1}" == "-" ]] && builtin cd "${OLDPWD}" && ls && return
    [[ -d "${1}" ]] && builtin cd "${1}" && ls && return
    [[ -f "${1}" ]] && builtin cd "${1%/*}" && ls && return
}

maketar() {
    tar cvzf "${1%%/}.tar.gz" "${1%%/}/"
}

makezip() {
    zipt -r "${1%%/}.zip" "${1}"
}

swap() {
     local TMPFILE=tmp.$$

     [[ $# -ne 2 ]] && printf 'swap: 2 arguments needed\n' && return 1
    # shellcheck disable=SC2016
     [[ ! -e "${1}" ]] && printf 'swap: ${1} does not exist\n' && return 1
    # shellcheck disable=SC2016
     [[ ! -e "${2}" ]] && printf 'swap: ${2} does not exist\n' && return 1

     mv "${1}" "${TMPFILE}"
     mv "${2}" "${1}"
     mv "${TMPFILE}" "${2}"
}

path() {
     printf '%s\n' "${PATH//:/\\n}"
}
