[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
key = "PageUp"
action = "ScrollPageUp"
mods = "Control"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollPageDown"
mods = "Control"
mode = "~Alt"

[[keyboard.bindings]]
key = "Home"
action = "ScrollToTop"
mods = "Control"
mode = "~Alt"

[[keyboard.bindings]]
key = "End"
action = "ScrollToBottom"
mods = "Control"
mode = "~Alt"
