#!/bin/bash

# Start polybar first
source ~/.config/polybar/launch.sh &

# Start Conky second
# source ~/.local/bin/conky-start &

# Set wallpaper
if [[ -f ~/.fehbg ]]; then
   source ~/.fehbg
else
   feh --bg-fill ~/Pictures/Wallpapers/Tate-McRae.jpg
fi &

# Xorg stuff
xsetroot -cursor_name left_ptr
xrdb -merge ~/.Xresources

pgrep bspswallow || bspswallow &

# Make sure sxhkd is always running
while :; do
   if pgrep -x sxhkd > /dev/null; then
      true
   else
      sxhkd &
   fi
   sleep 5
done &

# follow mouse for focus
bspc config focus_follows_pointer true

# Resize using the mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Confifuration
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 &
bspc config top_padding	40
bspc config bottom_padding	-8
bspc config border_width 2
bspc config window_gap 14
bspc config border_width 2
bspc config normal_border_color "#202020"
bspc config focused_border_color "#61AFEF"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Window rules
bspc rule -a fonky sticky=on manage=off lower=on
bspc rule -a gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a mpv state=fullscreen

# Auto-Start
urxvtc &
lxpolkit &
picom --config "$HOME/.config/picom/picom.conf" --experimental-backends > /dev/null &
gpaste-client daemon &
startup

# Move to Desktop 1
bspc desktop -f 1

# Set master stack layout
for ((i=1; i <= 8; i++)); {
   bsp-layout set tall ${i} --master-size 0.55
}

